#!/usr/bin/env bash
# This script installs and configures Nginx on a web server

sudo apt-get update
sudo apt-get install -y nginx

# Allow Nginx HTTP traffic
sudo ufw allow 'Nginx HTTP'

# Create a simple index.html file
echo "Hello World!" | sudo tee /var/www/html/index.html

# Test Nginx configuration
sudo nginx -t

# Reload Nginx service based on test result

sudo service nginx reload

