#!/usr/bin/env bash
# This script performs a 301 permanent move

sudo apt-get update
sudo apt-get install -y nginx

# Allow Nginx HTTP traffic
sudo ufw allow 'Nginx HTTP'

# Create a simple index.html file
echo "Hello World!" | sudo tee /var/www/html/index.html

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/MatthewZakari permanent;"

sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Test Nginx configuration
if sudo nginx -t; then
        # Ensure Nginx is configured to listen on port 80
        sudo sed -i 's/.*listen\s*80.*/listen 80;/g' /etc/nginx/sites-available/default

        # Reload Nginx service based on test result
        sudo service nginx restart
else
        echo "Nginx configuration test failed. Please check configuration."
fi
