#!/usr/bin/env bash
# 404 page customization script

sudo apt-get update
sudo apt-get install -y nginx

# Allow Nginx HTTP traffic
sudo ufw allow 'Nginx HTTP'

# Create a simple index.html file
echo "Hello World!" | sudo tee /var/www/html/index.html

# permanent redirectio
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/MatthewZakari permanent;"

sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# 404 error page customization
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Test Nginx configuration
if sudo nginx -t; then
        # Ensure Nginx is configured to listen on port 80
        sudo sed -i 's/.*listen\s*80.*/listen 80;/g' /etc/nginx/sites-available/default

        # Reload Nginx service based on test result
        sudo service nginx restart
else
        echo "Nginx configuration test failed. Please check configuration."
fi
